sonar.projectKey=mmatus0_documentalGPS
sonar.organization=mmatus0
sonar.sources=frontend/src,ms-auth,ms-mantenedores,gateway
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/tests/**,**/coverage/**
sonar.coverage.exclusions=frontend/src/**
sonar.javascript.lcov.reportPaths=ms-auth/coverage/lcov.info,ms-mantenedores/coverage/lcov.info