sonar.projectKey=mmatus0_documentalGPS
sonar.organization=mmatus0
 
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info